apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalogservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: productcatalogservice
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: productcatalogservice
    spec:
      containers:
        - image: 159616352881.dkr.ecr.eu-west-1.amazonaws.com/microservices-demo-productcatalogservice:latest
          name: productcatalogservice
          imagePullPolicy: Always
          resources: {}
          ports:
            - name: c-http
              containerPort: 3550
              protocol: TCP
